const test = require('node:test');
const assert = require('node:assert/strict');
const { renderProxyAdminPage } = require('./views/proxy-admin');
const { renderRuntimeLogsPage } = require('./views/runtime-logs');

test('renderProxyAdminPage should inject refresh interval', () => {
    const html = renderProxyAdminPage({ ui: { refreshMs: 4321 } });
    assert.equal(html.includes('4321ms'), true);
    assert.equal(html.includes('__REFRESH_MS__'), false);
    assert.equal(html.includes('IP价值榜（前100）'), true);
    assert.equal(html.includes('IP价值榜（前30）'), false);
    assert.equal(html.includes('/v1/proxies/value-board?limit=100'), true);
    assert.equal(html.includes('/v1/proxies/policy'), true);
    assert.equal(html.includes('/v1/proxies/recruit-camp'), true);
    assert.equal(html.includes('已退役：'), true);
    assert.equal(html.includes('active(新兵连)'), false);
    assert.equal(html.includes('退伍台账'), false);
    assert.equal(html.includes('代理明细（前50）'), false);
    assert.equal(html.includes('按价值分从高到低排的名次，1就是当前最有价值的IP。'), true);
    assert.equal(html.includes('系统一共'), true);
    assert.equal(html.includes("label: '编制'"), true);
    assert.equal(html.includes("label: '籍贯'"), true);
    assert.equal(html.includes("const displayNameWithBranch ="), false);
    assert.equal(html.includes(" + ' [' + serviceBranch + ']'"), false);
    assert.equal(html.includes("esc(displayName) + '</td>'"), true);
    assert.equal(html.includes("esc(serviceBranch) + '</td>'"), true);
    assert.equal(html.includes("function normalizeNativeTooltipText(value)"), true);
    assert.equal(html.includes("const nativeReadable = normalizeNativeTooltipText(x.native_lookup_readable_text);"), true);
    assert.equal(html.includes("const nativeRaw = normalizeNativeTooltipText(x.native_lookup_raw_json);"), true);
    assert.equal(html.includes("class=\"native-tooltip\""), true);
    assert.equal(html.includes("中文翻译"), true);
    assert.equal(html.includes("原始JSON"), true);
    assert.equal(html.includes("'<td class=\"native-cell\"><span class=\"native-place\">' + esc(nativePlace) + '</span>' + nativeTooltip + '</td>'"), true);
    assert.equal(html.includes("label: 'L0'"), true);
    assert.equal(html.includes("label: 'L1'"), true);
    assert.equal(html.includes("label: 'L2'"), true);
    assert.equal(html.includes("label: 'L3'"), true);
    assert.equal(html.includes("help: 'L0'"), true);
    assert.equal(html.includes("help: 'L1'"), true);
    assert.equal(html.includes("help: 'L2'"), true);
    assert.equal(html.includes("help: 'L3'"), true);
    assert.equal(html.includes('function fmtSuccessTotalPercent(success, total)'), true);
    assert.equal(html.includes("toFixed(1)"), true);
    assert.equal(html.includes("fmtSuccessTotalPercent(x.l0_success_count, l0Total)"), true);
    assert.equal(html.includes("fmtSuccessTotalPercent(x.l1_success_count, l1Total)"), true);
    assert.equal(html.includes("fmtSuccessTotalPercent(x.l2_success_count, l2Total)"), true);
    assert.equal(html.includes("fmtSuccessTotalPercent(x.l3_success_count, l3Total)"), true);
});

test('renderRuntimeLogsPage should return static html', () => {
    const html = renderRuntimeLogsPage();
    assert.equal(typeof html, 'string');
    assert.equal(html.includes('ProxyHub 中文实时日志'), true);
});
